debugging

diff --git a/python-service/template/.github/workflows/${{values.app_name}}-cicd.yaml b/python-service/template/.github/workflows/${{values.app_name}}-cicd.yaml
--- a/python-service/template/.github/workflows/${{values.app_name}}-cicd.yaml
+++ b/python-service/template/.github/workflows/${{values.app_name}}-cicd.yaml
@@ -38,6 +38,17 @@ jobs:
           push: true
           tags: doclosjs/${{values.app_name}}:${{ '${{env.COMMIT_ID}}' }}
       -
+      - name: Check token exists
+        run: |
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "❌ GITHUB_TOKEN is missing"
+            exit 1
+          else
+            echo "✅ GITHUB_TOKEN is set"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
+      -
         name: Register with releases
         shell: bash
         env:
